export const explorationTemplate1 = {
  id: "exploration_v1",
  name: "Template 1",
  description: "Polished geology/exploration figure layout for investor decks and press releases.",

  layout: {
    titleBlock: {
      anchor: "bottom-left",
      margin: { bottom: 80, left: 16 },
    },
    legend: {
      anchor: "bottom-left",
      margin: { bottom: 16, left: 16 },
    },
    logo: {
      anchor: "bottom-right",
      margin: { bottom: 16, right: 16 },
      maxWidth: 160,
    },
    northArrow: {
      anchor: "top-right",
      margin: { top: 16, right: 16 },
    },
    scaleBar: {
      anchor: "bottom-center",
      margin: { bottom: 16 },
    },
    insetMap: {
      anchor: "top-right",
      margin: { top: 72, right: 16 },
      width: 180,
      height: 140,
    },
  },

  titleBlockStyle: {
    background: "rgba(8, 30, 92, 0.94)",
    color: "#ffffff",
    borderRadius: 4,
    padding: "12px 16px",
    fontFamily: "Georgia, 'Times New Roman', serif",
    titleFontSize: 20,
    titleFontWeight: 700,
    subtitleFontSize: 12,
    subtitleOpacity: 0.85,
    maxWidth: 380,
  },

  legendStyle: {
    background: "rgba(255,255,255,0.96)",
    border: "1px solid #cad2df",
    borderRadius: 6,
    padding: "10px 14px",
    color: "#1b2533",
    fontFamily: "Arial, sans-serif",
    titleFontSize: 12,
    titleFontWeight: 700,
    itemFontSize: 12,
    maxWidth: 240,
    boxShadow: "0 2px 10px rgba(0,0,0,0.12)",
  },

  northArrowStyle: {
    background: "rgba(255,255,255,0.94)",
    border: "1px solid #cad2df",
    borderRadius: 6,
    padding: "8px 10px",
    color: "#111",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
  },

  scaleBarStyle: {
    background: "rgba(255,255,255,0.94)",
    border: "1px solid #cad2df",
    borderRadius: 6,
    padding: "8px 12px",
    color: "#111",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
  },

  insetMapStyle: {
    border: "2px solid #4a6fa5",
    borderRadius: 4,
    boxShadow: "0 2px 12px rgba(0,0,0,0.18)",
    background: "#eef2f7",
  },

  logoStyle: {
    background: "rgba(255,255,255,0.94)",
    border: "1px solid #cad2df",
    borderRadius: 6,
    padding: 8,
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
  },

  calloutStyle: {
    boxBackground: "#ffffff",
    boxBorder: "1.5px solid #2c3e50",
    boxBorderRadius: 4,
    boxPadding: "7px 10px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.15)",
    textColor: "#1a1a1a",
    titleFontSize: 12,
    titleFontWeight: 700,
    detailFontSize: 11,
    fontFamily: "Georgia, 'Times New Roman', serif",
    leaderColor: "#2c3e50",
    leaderWidth: 1.5,
    dotRadius: 4,
    dotFill: "#2c3e50",
  },

  defaultStyles: {
    claims: {
      stroke: "#2563eb",
      fill: "#2563eb",
      fillOpacity: 0.18,
      strokeWidth: 1.5,
      markerColor: "#2563eb",
      markerSize: 8,
      dashArray: "",
    },
    anomaly: {
      stroke: "#dc2626",
      fill: "#ef4444",
      fillOpacity: 0.28,
      strokeWidth: 1.5,
      markerColor: "#dc2626",
      markerSize: 8,
      dashArray: "6,4",
    },
    drillholes: {
      stroke: "#111111",
      fill: "#111111",
      fillOpacity: 1,
      strokeWidth: 1,
      markerColor: "#111111",
      markerSize: 6,
      dashArray: "",
    },
    drill_traces: {
      stroke: "#374151",
      fill: "#374151",
      fillOpacity: 0,
      strokeWidth: 1.5,
      markerColor: "#374151",
      markerSize: 6,
      dashArray: "4,3",
    },
    geophysics: {
      stroke: "#7c3aed",
      fill: "#8b5cf6",
      fillOpacity: 0.22,
      strokeWidth: 1,
      markerColor: "#7c3aed",
      markerSize: 6,
      dashArray: "",
    },
    highlight_zone: {
      stroke: "#d97706",
      fill: "#fbbf24",
      fillOpacity: 0.38,
      strokeWidth: 2,
      markerColor: "#d97706",
      markerSize: 8,
      dashArray: "",
    },
    other: {
      stroke: "#6b7280",
      fill: "#9ca3af",
      fillOpacity: 0.2,
      strokeWidth: 1.5,
      markerColor: "#6b7280",
      markerSize: 7,
      dashArray: "",
    },
  },
};
